### PR TITLE
implement Renly Baratheon (For Family Honor)

### PR DESCRIPTION
**Pull request by zacchiro**
To that end, raise a new onInsight event, carrying the list of cards drawn
using the Insight keyword.

Passing note: I find super annoying that the "drawn" parameter of the new event
is either a singleton element (a card) or an array of cards. But I've done it
that way for consistency with what we do for onPillage/discardFromDraw. IMHO
it'd be nice to uniform all of those to always return an array of cards.

### CODE REVIEW

**Comment by cryogen** [comment]
This potentially leaks game state to your opponent.  You'll only get the prompt if you draw a loyal card so your opponent can guess that youve drawn a loyal card if they see "waiting for opponent..."

**Comment by zacchiro** [comment]
On Sun, Feb 26, 2017 at 12:43:51PM -0800, Stuart Walsh wrote:
> This potentially leaks game state to your opponent.  You'll only get
> the prompt if you draw a loyal card so your opponent can guess that
> youve drawn a loyal card if they see "waiting for opponent..."

Good point. So, how do you want to go about avoiding this?

The first idea that comes to mind is *always* prompt the user, meaning
that if the controller chose to trigger when they've drawn a non-loyal
card, nothing would happen.  This would be more annoying in terms of
user experience than the current implementation, but it doesn't leak
info --- opponent cannot distinguish the situation in which you've drawn
a loyal card and decided not to trigger Renly, and the case you've drawn
a non loyal card.

Other ideas?

**Comment by cryogen** [comment]
What you said is all I could think of..

**Comment by zacchiro** [comment]
OK, adapted to do so.

**Pull request merged**
