### PR TITLE
Games List > A few style changes

### PR DESCRIPTION
**Pull request by xabiermartinez**
Minor fixes and contrast changes.

screenshot-localhost-4000-2017-04-24-14-17-42
screenshot-localhost-4000-2017-04-24-14-16-55

### CODE REVIEW

**Comment by cryogen** [comment]
Could you include a screenshot or two so I can see what the changes look like please? Thanks!

**Comment by xabiermartinez** [comment]
Sure, I'm at work, at the lunch time I could upload them.

**Comment by xabiermartinez** [comment]
Done!

**Comment by cryogen** [comment]
Hmm.  The game type is in the title on purpose to draw people's attention to it.  Also, the right hand side is pretty crowded already, especially on mobile

**Comment by xabiermartinez** [comment]
I moved game type because where it is has no visibility, even less being of the same colour. Being near join/watch buttons is useful, when you join/watch is when you want to know the game type. 
IMO the right hand side is clear, is the left side the crowded one.

**Comment by zacchiro** [comment]
FWIW, i agree with @xabiermartinez that where it is the game type is not really visible. While it is true that it currently appears *before* anything else, it gets visually lost within titles — that's why the other day I proposed to maybe change its font a little bit.

I don't know if moving the game type to the right is the nest solution (and I've no idea about the crowded aspect, given I always play on a desktop), but *some* way of making the game type stand out  from the title is needed.

**Comment by cryogen** [comment]
Going to leave this open so I don't lose it, I am going to do some of these changes :)

**Comment by xabiermartinez** [comment]
Sure.

**Comment by cryogen** [comment]
This has now been incorporated into a future change, or at least the bits i want to, for now

**Pull request closed without merging**
