### PR TITLE
Remove additional pile mechanism

### PR DESCRIPTION
**Pull request by ystros**
Removes the ability to create additional piles and nests all agenda
specific piles at the same level as the other piles under the
`Player` object.

### CODE REVIEW

**Comment by ystros** [comment]
This introduces breaking changes to how the client receives data and how the server sends it, so some caution needed during the deploy.

**Comment by cryogen** [comment]
I'd maybe go one step further and wrap them in a cardPiles object in getState()

**Comment by ystros** [comment]
Moved everything under `cardPiles` except faction, agenda and active plot (since they're all singular cards). I'd kind of like to do that with the server side piles as well, but the coupling directly is too great for the most part right now to be worth it.

**Comment by cryogen** [comment]
👍

**Pull request merged**
